from cycler import cycler

style = {
    "font.family": "serif",
    "font.serif": "cmr10",
    "font.size": 10,
    "figure.constrained_layout.use": True,
    "figure.autolayout": True,
    "savefig.bbox": "tight",
    "savefig.transparent": False,
    "axes.spines.left": True,
    "axes.spines.bottom": True,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.facecolor": "white",
    "axes.edgecolor": "black",
    "axes.grid": True,
    "axes.axisbelow": True,
    "axes.formatter.use_mathtext": True,
    "ytick.left": True,
    "xtick.bottom": True,
    "xtick.direction": "out",
    "ytick.direction": "out",
    "axes.prop_cycle": cycler(
        "color",
        [
            "#2F83B4",
            "#B5121B",
            "#F77F00",
            "#0B6E4F",
            "#7A68A6",
            "#C5BB36",
            "#8c564b",
            "#e377c2",
        ],
    ),
    "lines.color": "#B5121B",
    "image.cmap": "inferno",
    "grid.linestyle": "-",
    "grid.linewidth": 0.2,
    "grid.color": "#cbcbcb",
    "legend.frameon": True,
    "legend.loc": "best",
    "legend.fontsize": 10,
    "legend.fancybox": True,
    "legend.scatterpoints": 1,
    "legend.numpoints": 1,
    "legend.labelcolor": "black",
    "patch.antialiased": True,
}
